service: serverless-tutorial

provider:
  name: aws
  runtime: nodejs4.3

functions:
  getVehicle:
    handler: handler.getVehicle
    events:
    - http:
        path: vehicles/{vehicleID}
        method: get
  getSecurityDoors:
    handler: handler.getSecurityDoors
    events:
    - http:
        path: vehicles/{vehicleID}/doors
        method: get  


