service: serverless-tutorial

provider:
  name: aws
  runtime: nodejs4.3

functions:
  getVehicle:
    handler: handler.getVehicle
    events:
    - http:
        path: vehicles/{vehicleID}
        method: get
  getSecurityDoors:
    handler: handler.getSecurityDoors
    events:
    - http:
        path: vehicles/{vehicleID}/doors
        method: get
  getFuel:
    handler: handler.getFuel
    events:
    - http:
        path: vehicles/{vehicleID}/fuel
        method: get
  getBattery:
    handler: handler.getBattery
    events:
    - http:
        path: vehicles/{vehicleID}/battery
        method: get
  postEngine:
    handler: handler.postEngine
    events:
    - http:
        path: vehicles/{vehicleID}/engine
        method: post


